# This tells Nixpacks what commands to run to build the app.
# The order is important.
[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "playwright install-deps", 
    "playwright install chromium"
]
